ignore error if release doesn't have artifact

diff --git a/.github/workflows/publish-github-pages.yml b/.github/workflows/publish-github-pages.yml
--- a/.github/workflows/publish-github-pages.yml
+++ b/.github/workflows/publish-github-pages.yml
@@ -46,7 +46,9 @@ jobs:
             mkdir -p zig-out/www/downloads/microzig
 
             # Download the artifact 'boxzer-out.tar.gz' if it exists
-            gh release download "$release" --pattern "boxzer-out.tar.gz" --repo ${{ github.repository }} --dir .
+            if ! gh release download "$release" --pattern "boxzer-out.tar.gz" --repo ${{ github.repository }} --dir . ; then
+              # Continue if it fails
+            fi
 
             # Check if the tarball was downloaded and unpack it
             if [ -f "boxzer-out.tar.gz" ]; then
